export const APP_WRITE_ID = '66ea992e000c237d382a'
export const DB_ID = 'crm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
